language: node_js
node_js:
- '0.10'
before_script:
- gem update --system
- gem install bundler
- bundle -v
- npm install grunt-cli
deploy:
  provider: divshot
  environment:
    master: production
    staging: staging
    develop: development
  skip_cleanup: true
  api_key:
    secure: 0ll0oN31uESzANxRFh0PIV6exxLUCB0SqywcMsy58pvK/eapRVwXwyyKUFuQyLvArZmzeU7Nku6J+QYKqIdGSqWkCTprlhdXLN8yt4C2Lsv2yMhq+7d4qP43mppnTjrjVYN59I6mwkDfIVDVxsswqGui/fbpTsmymtfbl2peA6E=
