language: node_js
node_js:
- '0.10'
before_script:
- gem update --system
- bundle install
- npm install grunt-cli bower
- bower install
after_success:
- npm install -g firebase-tools
- grunt
- firebase deploy --token "${FIREBASE_TOKEN}"
