language: node_js

node_js:
  - 6

before_script:
- gem update --system
- bundle install
- npm install grunt-cli bower
- bower install

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    all_branches: true
    tags: true
    repo: kuatsure/thestylus
